Repository google/googletest, pull requests merged in 2019-06, with the labels that each got.

#2270 Don't allow signed/unsigned wchar_t in gcc 9 and later
  googlemock/include/gmock/internal/gmock-internal-utils.h
Labels: cla: yes, imported-into-CL, ready-to-import-merge-review

#2274 fix typo
  googlemock/docs/CookBook.md
Labels: cla: yes

#2268 Fuse gtest-spi.h into the resulting header.
  googletest/scripts/fuse_gtest_files.py
Labels: Conversation On-Going, cla: yes

#2283 Setting cmake CMP0054 policy to NEW
  googletest/cmake/internal_utils.cmake
Labels: cla: yes

#2285 Fixed issue #2284 (Incompatibility with C++17)
  googlemock/test/gmock-matchers_test.cc
Labels: cla: yes, imported-into-CL

#2286 Removing make and automake.
  .travis.yml
  Makefile.am
  ci/build-linux-autotools.sh
  configure.ac
  googlemock/Makefile.am
  googlemock/README.md
  googlemock/configure.ac
  googlemock/docs/CookBook.md
  googlemock/make/Makefile
  googlemock/scripts/gmock-config.in
  googletest/Makefile.am
  googletest/README.md
  googletest/configure.ac
  googletest/docs/Pkgconfig.md
  googletest/m4/acx_pthread.m4
  googletest/m4/gtest.m4
  googletest/make/Makefile
Labels: cla: yes

#2287 docs/primer: Fixed usage of test case
  googletest/docs/primer.md
Labels: cla: yes

#2296 Remove google internal links from documentation on github
  googletest/docs/advanced.md
  googletest/docs/faq.md
Labels: cla: yes
