Repository google/googletest, pull requests merged in 2019-02, with the labels that each got.

#2103 Fix an invalid example of JSON report in advanced.md
  googletest/docs/advanced.md
Labels: cla: yes

#2100 Test out changes with clang/OSX each PR using Travis CI
  .travis.yml
  ci/env-osx.sh
  ci/install-osx.sh
Labels: cla: yes

#2107 fix: Correct *-all.cc file paths
  library.json
Labels: cla: yes, imported-into-CL

#2113 Set gtest version correctly for older cmake versions
  googletest/CMakeLists.txt
Labels: cla: yes, imported-into-CL

#2119 Fix -Wunused-private-field issues with clang
  googlemock/test/gmock-matchers_test.cc
  googletest/test/googletest-param-test-test.cc
Labels: cla: yes, imported-into-CL

#2114 Generate a libgtest.la to help libtool managing dependencies
  googletest/cmake/libgtest.la.in
Labels: cla: yes

#2112 Stop TestInfo::Run() calling a function through null pointer
  googletest/src/gtest.cc
Labels: Conversation On-Going, cla: yes, imported-into-CL

#2141 Avoid array index out of range
  googletest/docs/primer.md
Labels: cla: yes

#2123 Fix clang `-Winconsistent-missing-override` warnings
  googlemock/test/gmock-matchers_test.cc
Labels: cla: yes, imported-into-CL

#2125 Fix clang `-Wunused-parameter` warnings
  googlemock/test/gmock-generated-matchers_test.cc
  googlemock/test/gmock-matchers_test.cc
Labels: cla: yes, imported-into-CL

#2061 Enable building as a shared library (dll) on Windows with Bazel
  BUILD.bazel
  appveyor.yml
Labels: cla: yes, imported-into-CL

#2137 Ignore `-Wsign-conversion` issues
  googletest/cmake/internal_utils.cmake
Labels: cla: yes, imported-into-CL

#2147 Don't hardcode the filename in `CxxExceptionDeathTest.PrintsMessageForStdException`
  googletest/test/googletest-death-test_ex_test.cc
Labels: cla: yes, imported-into-CL

#2152 Fix grammatical error in primer.md
  googletest/docs/primer.md
Labels: cla: yes
