Repository google/googletest, pull requests merged in 2019-08, with the labels that each got.

#2353 Update README.md (issue #2352)
  googlemock/README.md
Labels: Conversation On-Going, cla: yes

#2361 Fix table formatting in advanced.md
  googletest/docs/advanced.md
Labels: cla: yes

#2357 Update pre-C++11 paragraphs
  googlemock/include/gmock/gmock-generated-actions.h
  googlemock/include/gmock/gmock-generated-actions.h.pump
  googlemock/include/gmock/gmock-generated-matchers.h
  googlemock/include/gmock/gmock-generated-matchers.h.pump
Labels: Conversation On-Going, cla: yes, imported-into-CL

#2341 Formatting in primer.md
  googletest/docs/primer.md
Labels: Conversation On-Going, cla: yes, maybe close

#2358 Adjustment of two similar comments
  googletest/include/gtest/gtest-typed-test.h
Labels: cla: yes

#2111 Remove / from parameterized test names if base test name is empty
  googletest/include/gtest/internal/gtest-param-util.h
  googletest/test/googletest-output-test-golden-lin.txt
  googletest/test/googletest-output-test_.cc
Labels: Conversation On-Going, cla: yes, imported-into-CL

#2359 Remove an excessive mutable type specifier
  googlemock/include/gmock/gmock-spec-builders.h
Labels: Conversation On-Going, cla: yes, imported-into-CL

#2375 Fix broken links
  CONTRIBUTING.md
  googlemock/scripts/fuse_gmock_files.py
Labels: cla: yes

#2372 Fix #2371: Redirect Windows CRT assertions to stderr
  googletest/src/gtest.cc
  googletest/test/googletest-death-test-test.cc
Labels: cla: yes

#2378 Fix an improperly generated table
  googletest/docs/primer.md
Labels: cla: yes, imported-into-CL

#2386 Remove an outdated comment
  googletest/include/gtest/gtest-typed-test.h
Labels: cla: yes, imported-into-CL

#2399 Remove custom implementations of std::is_same
  googlemock/include/gmock/gmock-spec-builders.h
  googlemock/include/gmock/internal/gmock-internal-utils.h
  googlemock/test/gmock-internal-utils_test.cc
  googlemock/test/gmock-matchers_test.cc
  googletest/include/gtest/gtest-matchers.h
  googletest/include/gtest/internal/gtest-internal.h
  googletest/include/gtest/internal/gtest-port.h
  googletest/test/googletest-output-test_.cc
  googletest/test/gtest-typed-test_test.cc
Labels: cla: yes, imported-into-CL

#2391 Use -Wa,-mbig-obj for Cygwin/MinGW always
  googlemock/CMakeLists.txt
Labels: cla: yes, imported-into-CL

#2393 Remove a custom implementation of std::remove_const
  googlemock/include/gmock/gmock-matchers.h
  googlemock/include/gmock/internal/gmock-internal-utils.h
  googletest/include/gtest/internal/gtest-internal.h
  googletest/test/gtest_unittest.cc
Labels: cla: yes, imported-into-CL

#2401 Remove a custom implementation of std::add_lvalue_reference
  googletest/include/gtest/internal/gtest-port.h
  googletest/test/gtest_unittest.cc
Labels: cla: yes, imported-into-CL

#2394 Reuse IndexSequence from googletest
  googlemock/include/gmock/internal/gmock-internal-utils.h
Labels: cla: yes, imported-into-CL

#2382 Remove a dead metafunction
  googlemock/include/gmock/internal/gmock-internal-utils.h
Labels: cla: yes, imported-into-CL

#2426 Post-review to #2396
  googlemock/include/gmock/gmock-matchers.h
Labels: cla: yes, imported-into-CL

#2420 Remove references to autotools and combine gTest & gMock sections
  CONTRIBUTING.md
Labels: cla: yes
