Repository google/googletest, pull requests merged in 2019-03, with the labels that each got.

#2158 Minor build system fixes.
  .gitignore
  Makefile.am
  googlemock/Makefile.am
  googlemock/configure.ac
  googletest/configure.ac
Labels: cla: yes, imported-into-CL

#2181 DesignDoc Markdown table was broken
  googlemock/docs/DesignDoc.md
Labels: cla: yes

#2193 Note about INSTANTIATE_TEST_SUITE_P / INSTANTIATE_TEST_CASE_P
  googletest/docs/advanced.md
Labels: Conversation On-Going, cla: yes

#2199 Update Xcode project file
  googletest/xcode/gtest.xcodeproj/project.pbxproj
Labels: cla: yes
