Repository google/googletest, pull requests merged in 2020-03, with the labels that each got.

#2723 Fixed warnings
  googletest/src/gtest.cc
Labels: cla: yes

#2716 Remove a dead reference to the Autotools script
  googletest/README.md
Labels: cla: yes, imported-into-CL

#2722 Fixed warnings
  googletest/src/gtest.cc
Labels: cla: yes, imported-into-CL

#2746 Make sure IsATTY does not clobber errno.
  googletest/include/gtest/internal/gtest-port.h
Labels: cla: yes, imported-into-CL

#2350 Add support for std::function in MockFunction (#2277)
  googlemock/include/gmock/gmock-spec-builders.h
  googlemock/test/gmock-function-mocker_test.cc
Labels: Conversation On-Going, cla: yes

#2764 Remove dead code in googletest-output-test
  googletest/test/googletest-output-test_.cc
Labels: cla: yes, imported-into-CL

#2765 Remove chapters on unsupported build systems (Autotools, Meson and plain Makefiles)
  googletest/docs/pkgconfig.md
Labels: cla: yes, imported-into-CL
