Repository google/googletest, pull requests merged in 2021-11, with the labels that each got.

#3638 Re #3637 Show Disabled Tests in testing output
  googletest/include/gtest/gtest.h
  googletest/src/gtest.cc
Labels: cla: yes, imported-into-CL

#3657 googletest/src/gtest-port.cc: Added GetLastError() on Windows
  googletest/src/gtest-port.cc
Labels: cla: yes

#3650 Replace use of deprecated std::iterator
  googlemock/test/gmock-matchers_test.cc
Labels: cla: yes, imported-into-CL

#3672 Suppress unused-value warning
  googletest/src/gtest-port.cc
Labels: cla: yes

#3669 fixed branch from master to main in readme.md
  README.md
Labels: cla: yes

#3664 Fix a typo
  googlemock/src/gmock-spec-builders.cc
Labels: cla: yes

#3620 Start a simple github actions CI
  .github/workflows/gtest-ci.yml
Labels: cla: yes, ready to pull
